// ---------------------------------------------------------------------------
// StockSense master-data + operations-history seeder.
//
// Idempotent: deletes the demo-owned rows (matched by the prefixes below) and
// re-inserts, so reruns are safe.
//
// Pipeline order (each step needs the previous one's ids):
//   1. users  2. virtual locations  3. warehouses  4. internal locations
//   5. categories  6. products  7. stock quants  8. operations + ledger moves
//
// The DATA itself is generated by the pure modules demoCatalog.js and
// demoOperations.js — this file only persists it. That split is deliberate:
// the interesting logic is unit-testable without a database, and the PRNG draw
// order lives in exactly one place per dataset.
//
// All data is FICTIONAL-BUT-PLAUSIBLE demo data for the StockSense hackathon
// demo. Companies, GSTINs, and partner names are illustrative.
// ---------------------------------------------------------------------------
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import mongoose from 'mongoose';
import connectDB from '../config/db.config.js';
import User from '../models/user.model.js';
import Warehouse from '../models/warehouse.model.js';
import Location from '../models/location.model.js';
import ProductCategory from '../models/productCategory.model.js';
import Product from '../models/product.model.js';
import StockQuant from '../models/stockQuant.model.js';
import StockOperation from '../models/stockOperation.model.js';
import StockMove from '../models/stockMove.model.js';
import VendorPrice from '../models/vendorPrice.model.js';
import { generateCatalog, CATEGORIES, DEMO_PASSWORD, DATASET_VERSION, PARTNER_NAMES } from './demoCatalog.js';
import { generateOperationsHistory, HISTORY_DAYS } from './demoOperations.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
// Local backend/.env overrides the shared repo-root .env; dotenv does not
// clobber already-set vars, so the local file is loaded first.
dotenv.config({ path: path.resolve(__dirname, '../../.env') });
dotenv.config({ path: path.resolve(__dirname, '../../../.env') });

// Rows this seeder owns. Everything else in the DB is left alone.
const DEMO_WAREHOUSE_CODES = ['WH1', 'WH2', 'WH3', 'WH4'];
const DEMO_LOCATION_RE = /^(WH[1-4]\/|PARTNER\/|VIRTUAL\/)/;
const DEMO_OPERATION_RE = /^(REC|DEL|INT|ADJ)\/2026\//;
const DEMO_CATEGORY_NAMES = CATEGORIES.map((c) => c.name);
const DEMO_SKU_RE = /^(STEEL|ALUM|BOLT|CHAIR|FRAME|PASTE|HELM|TUBE|ANGLE|WIRE|CABLE|SWITCH|LIGHT|CONDUIT|CARTON|WRAP|TAPE|PALLET|LABEL|PPE|SAFETY|TABLE|SHELF|BIN|DOLLY|MAT|PACK|ADHESIVE|RESIN|ABRASIVE|SOLDER|LUBE)/;

/**
 * Which warehouse a category's home shelf lives in. Drives the second
 * reordering rule and the secondary stock holdings, so the multi-warehouse
 * dashboard and warehouse filter have something real to show.
 */
function homeWarehouseFor(categoryKey) {
  const map = {
    metals: 'wh2', hardware: 'wh1', electrical: 'wh3', packaging: 'wh2',
    safety: 'wh3', furniture: 'wh4', raw: 'wh3', finished: 'wh1',
  };
  return map[categoryKey] ?? 'wh1';
}

// Secondary warehouse holdings, so the warehouse filter and the per-warehouse
// totals view are not empty for the lines that matter.
const SECONDARY_HOLDINGS = [
  { key: 'steel', loc: 'wh2_stock', qty: 50 },
  { key: 'steelplate', loc: 'wh2_stock', qty: 380 },
  { key: 'alum', loc: 'wh2_stock', qty: 30 },
  { key: 'cartonS', loc: 'wh3_stock', qty: 210 },
  { key: 'cartonL', loc: 'wh3_stock', qty: 95 },
  { key: 'stretchwrap', loc: 'wh2_rackC', qty: 40 },
  { key: 'gloves', loc: 'wh3_rackE', qty: 60 },
  { key: 'vest', loc: 'wh3_rackE', qty: 35 },
  { key: 'cable', loc: 'wh3_rackD', qty: 140 },
  { key: 'table', loc: 'wh4_rackF', qty: 9 },
  { key: 'shelfunit', loc: 'wh4_rackF', qty: 14 },
];

const seedDatabase = async () => {
  try {
    console.log(`--- StockSense demo seeder (${DATASET_VERSION}) ---`);
    await connectDB();
    if (mongoose.connection.readyState !== 1) {
      throw new Error('not connected to MongoDB — check MONGO_URI / MONGODB_URI in backend/.env');
    }

    // ---- 0. Clean previous demo data (idempotent) ----------------------
    console.log('--- 0. Cleaning previous demo data ---');
    // VendorPrice rows are deleted by their own seeder (seedVendors.js), but
    // this seeder deletes the Products they point at and recreates them with
    // NEW ObjectIds. Any price row left over would keep referencing a dead
    // product id — the collection would still look populated while no product
    // actually has vendors. Drop the orphans here so a reseed can never leave
    // the vendor layer silently broken. seedVendors.js re-creates them.
    const stalePrices = await VendorPrice.deleteMany({});
    const removed = await Promise.all([
      User.deleteMany({ email: /@stocksense\.com$/ }),
      Warehouse.deleteMany({ code: { $in: DEMO_WAREHOUSE_CODES } }),
      Location.deleteMany({ code: DEMO_LOCATION_RE }),
      ProductCategory.deleteMany({ name: { $in: DEMO_CATEGORY_NAMES } }),
      Product.deleteMany({ sku: DEMO_SKU_RE }),
      StockQuant.deleteMany({}),
      StockOperation.deleteMany({ reference: DEMO_OPERATION_RE }),
      StockMove.deleteMany({ reference: DEMO_OPERATION_RE }),
    ]);
    console.log(
      `  removed: prices=${stalePrices.deletedCount} users=${removed[0].deletedCount} ` +
      `wh=${removed[1].deletedCount} loc=${removed[2].deletedCount} cat=${removed[3].deletedCount} ` +
      `prod=${removed[4].deletedCount} quant=${removed[5].deletedCount} op=${removed[6].deletedCount} ` +
      `move=${removed[7].deletedCount}`
    );
    console.log('  NOTE: run seedVendors.js next — it re-creates the vendor price quotes this drop removed.');

    // ---- Generate the dataset (pure) ----------------------------------
    const catalog = generateCatalog();
    const internalLocationKeys = catalog.locations.map((l) => l.key);

    // ---- 1. Users ------------------------------------------------------
    console.log('--- 1. Seeding demo users ---');
    // The User model hashes `password_hash` in a pre-save hook and the field
    // is required, so the plaintext demo password is assigned to
    // `password_hash` and hashed on insert.
    const userDocs = await User.create(
      catalog.users.map((u) => ({
        name: u.name,
        email: u.email,
        password_hash: u.password_hash,
        role: u.role,
        is_email_verified: true,
        email_verified_at: new Date(),
        status: 'active',
      }))
    );
    console.log(`  ${userDocs.length} users`);

    // ---- 2. Virtual / partner locations --------------------------------
    console.log('--- 2. Seeding virtual locations ---');
    const virtualDocs = await Location.create(
      catalog.virtualLocations.map((v) => ({
        name: v.name,
        code: v.code,
        location_type: v.location_type,
      }))
    );
    const virtualIdByKey = Object.fromEntries(
      catalog.virtualLocations.map((v, i) => [v.key, virtualDocs[i]._id])
    );

    // ---- 3. Warehouses --------------------------------------------------
    console.log('--- 3. Seeding warehouses ---');
    const warehouseDocs = await Warehouse.create(
      catalog.warehouses.map((w) => ({ name: w.name, code: w.code, address: w.address }))
    );
    const warehouseIdByKey = Object.fromEntries(
      catalog.warehouses.map((w, i) => [w.key, warehouseDocs[i]._id])
    );
    console.log(`  ${warehouseDocs.length} warehouses`);

    // ---- 4. Internal locations ------------------------------------------
    console.log('--- 4. Seeding internal locations ---');
    const locationDocs = await Location.create(
      catalog.locations.map((l) => ({
        warehouse: warehouseIdByKey[l.warehouse],
        name: l.name,
        code: l.code,
        location_type: 'internal',
        zone: l.zone,
        aisle: l.aisle,
        rack: l.rack,
        shelf: l.shelf,
        position_index: l.position_index,
        max_capacity: l.capacity,
      }))
    );
    const locationIdByKey = Object.fromEntries(catalog.locations.map((l, i) => [l.key, locationDocs[i]._id]));
    const allLocationIdByKey = { ...locationIdByKey, ...virtualIdByKey };
    console.log(`  ${locationDocs.length} internal locations`);

    // ---- 5. Categories (parents before children) ------------------------
    console.log('--- 5. Seeding product categories ---');
    const categoryIdByKey = {};
    const orderedCategories = [
      ...catalog.categories.filter((c) => !c.parentKey),
      ...catalog.categories.filter((c) => c.parentKey),
    ];
    for (const c of orderedCategories) {
      const doc = await ProductCategory.create({
        name: c.name,
        parent: c.parentKey ? categoryIdByKey[c.parentKey] : null,
        description: c.description,
      });
      categoryIdByKey[c.key] = doc._id;
    }
    console.log(`  ${Object.keys(categoryIdByKey).length} categories`);

    // ---- 6. Products ---------------------------------------------------
    console.log('--- 6. Seeding products ---');
    const productDocs = await Product.create(
      catalog.products.map((p) => ({
        name: p.name,
        sku: p.sku,
        category: categoryIdByKey[p.category],
        uom: p.uom,
        description: p.description,
        is_active: true,
        // Anchor SKUs keep their original single WH1 rule; extended products
        // get WH1 plus their category's home warehouse, so the per-warehouse
        // reorder view has real multi-site rules to compare.
        reordering_rules: p.anchor
          ? [{ warehouse: warehouseIdByKey.wh1, min_quantity: p.min_quantity, max_quantity: p.max_quantity }]
          : [
              { warehouse: warehouseIdByKey.wh1, min_quantity: p.min_quantity, max_quantity: p.max_quantity },
              { warehouse: warehouseIdByKey[homeWarehouseFor(p.category)], min_quantity: p.min_quantity, max_quantity: p.max_quantity },
            ],
      }))
    );
    const productIdByKey = Object.fromEntries(catalog.products.map((p, i) => [p.key, productDocs[i]._id]));
    const anchorCount = catalog.products.filter((p) => p.anchor).length;
    console.log(`  ${productDocs.length} products (${anchorCount} SVR-covered + ${productDocs.length - anchorCount} baseline)`);

    // ---- 7. Stock quants ------------------------------------------------
    console.log('--- 7. Seeding stock quants ---');
    // StockQuant has a unique (product, location) index, so secondary holdings
    // that land on the SAME rack the catalog already placed the product on
    // would be a duplicate-key error. The catalog's location choice is derived
    // deterministically from the category, so rather than hardcoding a
    // "safe" rack here and hoping it never collides, merge by key: a secondary
    // holding wins the quantity if it targets a different rack, and is
    // skipped (with a log line) if the catalog already placed it there.
    const quantRows = catalog.stock.map((s) => ({
      productKey: s.productKey,
      locationKey: s.locationKey,
      quantity: s.quantity,
      reserved_quantity: s.reserved_quantity,
      origin: 'catalog',
    }));
    for (const s of SECONDARY_HOLDINGS) {
      if (!productIdByKey[s.key] || !locationIdByKey[s.loc]) continue;
      const existing = quantRows.find((q) => q.productKey === s.key && q.locationKey === s.loc);
      if (existing) {
        console.log(`  skip secondary holding ${s.key} @ ${s.loc} — already stocked there`);
        continue;
      }
      quantRows.push({
        productKey: s.key,
        locationKey: s.loc,
        quantity: s.qty,
        reserved_quantity: 0,
        origin: 'secondary',
      });
    }
    const uniqueQuants = quantRows.filter(
      (q, i) => quantRows.findIndex((o) => o.productKey === q.productKey && o.locationKey === q.locationKey) === i
    );
    await StockQuant.create(
      uniqueQuants.map((q) => ({
        product: productIdByKey[q.productKey],
        location: locationIdByKey[q.locationKey],
        quantity: q.quantity,
        reserved_quantity: q.reserved_quantity,
      }))
    );
    console.log(`  ${uniqueQuants.length} stock quants (${uniqueQuants.length - catalog.stock.length} secondary warehouse holdings)`);

    // ---- 8. Operations + ledger moves -----------------------------------
    console.log(`--- 8. Generating ${HISTORY_DAYS} days of operations history ---`);
    const opsData = generateOperationsHistory({
      products: catalog.products,
      internalLocationKeys,
      vendorLocKey: 'vendor',
      customerLocKey: 'customer',
      lossLocKey: 'loss',
      userCount: userDocs.length,
      suppliers: PARTNER_NAMES.suppliers,
      customers: PARTNER_NAMES.customers,
    });

    const operationDocs = await StockOperation.create(
      opsData.operations.map((op) => ({
        reference: op.reference,
        operation_type: op.operation_type,
        status: op.status,
        partner_name: op.partner_name,
        source_location: allLocationIdByKey[op.sourceKey],
        destination_location: allLocationIdByKey[op.destinationKey],
        created_by: userDocs[op.createdByIndex]._id,
        created_at: op.created_at,
        scheduled_date: op.scheduled_date,
        validated_at: op.validated_at,
        notes: op.notes,
        lines: op.lines.map((l) => ({
          product: productIdByKey[l.productKey],
          quantity_demanded: l.quantity_demanded,
          quantity_done: l.quantity_done,
        })),
      }))
    );
    const operationIdByRef = Object.fromEntries(operationDocs.map((o) => [o.reference, o._id]));

    await StockMove.insertMany(
      opsData.moves.map((mv) => ({
        reference: mv.reference,
        operation: operationIdByRef[mv.reference] || null,
        product: productIdByKey[mv.productKey],
        source_location: allLocationIdByKey[mv.sourceKey],
        destination_location: allLocationIdByKey[mv.destinationKey],
        quantity: mv.quantity,
        status: mv.status,
        move_date: mv.move_date,
        user: userDocs[mv.createdByIndex]._id,
      }))
    );
    console.log(`  ${operationDocs.length} operations, ${opsData.moves.length} ledger moves`);
    console.log(`  by type:   ${JSON.stringify(opsData.summary.byType)}`);
    console.log(`  by status: ${JSON.stringify(opsData.summary.byStatus)}`);

    // ---- Summary ---------------------------------------------------------
    console.log('\n======================================================');
    console.log(' DATABASE SEEDED SUCCESSFULLY WITH DEMO DATA!');
    console.log('======================================================');
    console.log(`  Dataset:      ${DATASET_VERSION}`);
    console.log(`  Users:        ${userDocs.length}`);
    console.log(`  Warehouses:   ${warehouseDocs.length} (WH1..WH4)`);
    console.log(`  Locations:    ${locationDocs.length} internal + ${virtualDocs.length} virtual`);
    console.log(`  Categories:   ${Object.keys(categoryIdByKey).length}`);
    console.log(`  Products:     ${productDocs.length} (${anchorCount} SVR + ${productDocs.length - anchorCount} baseline)`);
    console.log(`  Stock quants: ${uniqueQuants.length}`);
    console.log(`  Operations:   ${operationDocs.length} over ${HISTORY_DAYS} days`);
    console.log(`  Ledger moves: ${opsData.moves.length}`);
    console.log('------------------------------------------------------');
    console.log(`DEMO ACCOUNTS (password: ${DEMO_PASSWORD})`);
    for (const u of catalog.users) {
      console.log(`  ${u.role.padEnd(18)} ${u.email}`);
    }
    console.log('======================================================\n');

    await mongoose.connection.close();
    process.exit(0);
  } catch (error) {
    console.error('Seeding Failed:', error);
    await mongoose.connection.close();
    process.exit(1);
  }
};

seedDatabase();
